AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloudformation for ausgreener webapp"
Transform: AWS::Serverless-2016-10-31
Parameters:

    DomainName:
        Type: String
        Default: zachjbrowning.com

    TemplateBaseUrl:
        Type: String
        Default: https://ausgreener-build-resources.s3.ap-southeast-2.amazonaws.com/infrastructure/infra/cloudformation

Resources:
    
    Infrastructure:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Retain
        Properties:
            Parameters:
                DomainName: !Ref DomainName
                PipelineScheduleRoleArn: !GetAtt Roles.Outputs.PipelineScheduleRoleArn
            TemplateURL: !Sub "${TemplateBaseUrl}/infrastructure.yml"


