AWSTemplateFormatVersion: "2010-09-09"
Description: "Networking for zachjbrowning.com"
Parameters:

    DomainName: 
        Type: String
        Default: zachjbrowning.com

    CloudFrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            DistributionConfig: 
                Enabled: true
                Aliases: 
                  - !Sub "www.${DomainName}"
                  - !Sub "${DomainName}"
                Origins: 
                  - 
                    ConnectionAttempts: 3
                    ConnectionTimeout: 9
                    CustomOriginConfig: 
                        HTTPPort: 80
                        HTTPSPort: 443
                        OriginKeepaliveTimeout: 5
                        OriginProtocolPolicy: "http-only"
                        OriginReadTimeout: 30
                        OriginSSLProtocols: 
                          - "TLSv1"
                          - "TLSv1.1"
                          - "TLSv1.2"
                    DomainName: !Sub "${DomainName}.s3-website-${AWS::Region}.amazonaws.com"
                    Id: !Sub "${DomainName}.s3-website-${AWS::Region}.amazonaws.com"
                    OriginPath: ""
                OriginGroups: 
                    Quantity: 0
                DefaultCacheBehavior: 
                    AllowedMethods: 
                      - "HEAD"
                      - "GET"
                    CachedMethods: 
                      - "HEAD"
                      - "GET"
                    Compress: true
                    CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
                    SmoothStreaming: false
                    TargetOriginId: !Sub "${DomainName}.s3-website-${AWS::Region}.amazonaws.com"
                    ViewerProtocolPolicy: "redirect-to-https"
                CustomErrorResponses: 
                  - 
                    ErrorCode: 404
                    ResponsePagePath: "/index.html"
                    ResponseCode: "200"
                    ErrorCachingMinTTL: 10
                Comment: ""
                PriceClass: "PriceClass_All"
                ViewerCertificate: 
                    AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/3cda888e-908a-405b-87b6-a12342e1ecfb"
                    MinimumProtocolVersion: "TLSv1.2_2021"
                    SslSupportMethod: "sni-only"
                Restrictions: 
                    GeoRestriction: 
                        RestrictionType: "none"
                HttpVersion: "http2"
                DefaultRootObject: ""
                IPV6Enabled: true