//EXAMPLES
export const SPINNER_TOGGLE = 'SPINNER_TOGGLE';


// Project 
export const LOAD_PROJECTS = 'LOAD_PROJECTS';

// RECIPES
export const LOAD_RECIPES = 'LOAD_RECIPES';

// CONTACT
export const LOAD_CONTACT = 'LOAD_CONTACT';

// ACTIVE
export const SET_ACTIVE = 'SET_ACTIVE';
export const UNSET_ACTIVE = 'UNSET_ACTIVE';