version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      - cd

artifacts:
  files:
    - '**.*'
  secondary-artifacts:
    infrastructureBuild:
      files:
        - ./infra/cloudformation/*
        

cache:
  paths:
    - './node_modules/**/*'
