version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      - yarn build
      - cd dist
      - zip -qr build.zip ./*
      - mb build.zip ..
      - cd ..
      - mkdir deploy-lambda-output
      - cp infra/lambda/DeployStaticFiles.py deploy-lambda-output
      - cd deploy-lambda-output
      - zip -qr deploy-lambda.zip ./*
      - mv deploy-lambda.zip ..


  build:
    commands:
      - cd

artifacts:
  files:
    - '**.*'
  secondary-artifacts:
    infrastructureBuild:
      files:
        - ./infra/cloudformation/*
    deployLambdaBuild:
      files:
        - deploy-lambda.zip
    staticFilesBuild:
      files:
        - build.zip
        

cache:
  paths:
    - './node_modules/**/*'
